{'stackTrace', 'errorType', 'errorMessage'} in {'errorMessage': 'Unsupported type "<class \'datetime.datetime\'>" for value "2022-02-12 05:13:05.343365"', 'errorType': 'TypeError', 'stackTrace': ['  File "/var/task/app.py", line 44, in lambda_handler\n    resp = table.put_item(Item={"ID": id, "Time": datetime.datetime.now()})\n', '  File "/var/task/boto3/resources/factory.py", line 520, in do_action\n    response = action(self, *args, **kwargs)\n', '  File "/var/task/boto3/resources/action.py", line 83, in __call__\n    response = getattr(parent.meta.client, operation_name)(*args, **params)\n', '  File "/var/task/botocore/client.py", line 391, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n', '  File "/var/task/botocore/client.py", line 691, in _make_api_call\n    request_dict = self._convert_to_request_dict(\n', '  File "/var/task/botocore/client.py", line 737, in _convert_to_request_dict\n    api_params = self._emit_api_params(\n', '  File "/var/task/botocore/client.py", line 766, in _emit_api_params\n    self.meta.events.emit(\n', '  File "/var/task/botocore/hooks.py", line 357, in emit\n    return self._emitter.emit(aliased_event_name, **kwargs)\n', '  File "/var/task/botocore/hooks.py", line 228, in emit\n    return self._emit(event_name, kwargs)\n', '  File "/var/task/botocore/hooks.py", line 211, in _emit\n    response = handler(**kwargs)\n', '  File "/var/task/boto3/dynamodb/transform.py", line 195, in inject_attribute_value_input\n    self._transformer.transform(\n', '  File "/var/task/boto3/dynamodb/transform.py", line 253, in transform\n    self._transform_parameters(\n', '  File "/var/task/boto3/dynamodb/transform.py", line 260, in _transform_parameters\n    getattr(self, \'_transform_%s\' % type_name)(\n', '  File "/var/task/boto3/dynamodb/transform.py", line 274, in _transform_structure\n    self._transform_parameters(\n', '  File "/var/task/boto3/dynamodb/transform.py", line 260, in _transform_parameters\n    getattr(self, \'_transform_%s\' % type_name)(\n', '  File "/var/task/boto3/dynamodb/transform.py", line 285, in _transform_map\n    params[key] = transformation(value)\n', '  File "/var/task/boto3/dynamodb/types.py", line 105, in serialize\n    dynamodb_type = self._get_dynamodb_type(value)\n', '  File "/var/task/boto3/dynamodb/types.py", line 144, in _get_dynamodb_type\n    raise TypeError(msg)\n']}